version: "3.7"
services:
  api:
    image: "node:14-alpine"
    command: yarn start:dev
    env_file:
      - $PWD/.env
    environment:
      - NODE_SCRIPT=./dist/server/cjs.js
    secrets:
      - mysql
      - postgres
    volumes:
      - $PWD/node_modules:/node/app/node_modules
      - $PWD/../node_modules:/node/node_modules
      - $PWD/dist:/node/app/dist
      - $PWD/package.json:/node/app/package.json
    working_dir: /node/app
